sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t andyandria/docker-react -f Dockerfile.dev

script:
  - docker run -e CI=true andyandria/docker-react npm run test
